utilitools.fileManager.utilitools.configHelpers.load()
local configHelpers = utilitools.configHelpers
configHelpers.setMod(mod)

configHelpers.treeNode("Menu Options", function()
	configHelpers.presets.menuOptions()
	imgui.Separator()
	configHelpers.presets.menuButtons()
end, 2 ^ 5)
configHelpers.treeNode("Advanced", function()
	configHelpers.input("isolateLogs")
    configHelpers.input("modPath")
	configHelpers.input("reloadHotkey")
end)
configHelpers.treeNode("Search", function()
	configHelpers.presets.search()
end)
configHelpers.condTreeNode("Full Mod Description", "documentation", "none", false, function()
	configHelpers.doc("fullDescription")
end)
